/**
 * ExecutiveSummary — the header card shown at the top of every report.
 *
 * Server-safe (no hooks). Renders the compliance score, severity counts,
 * EAA readiness badge, and quick-wins/top-priority lists.
 *
 * Props: pass the full ExecutiveSummary object from report-mapper + scan metadata.
 */

import type { ExecutiveSummary } from '@/types/report';

interface ExecutiveSummaryProps {
  summary: ExecutiveSummary;
  url: string;
  scannedAt: string;
  reportId?: string; // used for PDF/copy links — optional for sample report
}

function scoreColor(s: number) {
  return s >= 80 ? 'text-green-mid' : s >= 50 ? 'text-warn' : 'text-fail';
}
function scoreBarColor(s: number) {
  return s >= 80 ? '#16A34A' : s >= 50 ? '#D97706' : '#DC2626';
}
function formatDate(iso: string) {
  return new Date(iso).toLocaleString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

export default function ExecutiveSummary({
  summary,
  url,
  scannedAt,
  reportId,
}: ExecutiveSummaryProps) {
  const {
    score,
    critical_count,
    should_fix_count,
    nice_to_have_count,
    passed_checks,
    eaa_ready,
  } = summary;

  const nextStepsText =
    critical_count > 0
      ? `Start with the ${critical_count} Critical issue${critical_count > 1 ? 's' : ''}. These block users entirely and carry legal risk under the EAA.${should_fix_count > 0 ? ` Then work through the ${should_fix_count} Should Fix item${should_fix_count > 1 ? 's' : ''} to reach full EAA compliance.` : ' Once resolved, your site will meet the EAA baseline.'}`
      : should_fix_count > 0
        ? `No critical issues — well done. Work through the ${should_fix_count} Should Fix item${should_fix_count > 1 ? 's' : ''} to reach full EAA compliance.`
        : 'No critical or required issues. Your site is in excellent shape for EAA compliance.';

  return (
    <div className="corner-mark border border-border bg-surface">
      <div className="px-6 pt-6 pb-4">

        {/* Header row */}
        <div className="flex items-center gap-3 mb-4 flex-wrap">
          <span className="font-mono text-xs tracking-widest uppercase text-green">
            Accessibility Report
          </span>
          {eaa_ready ? (
            <span className="font-mono text-[10px] uppercase tracking-widest px-2 py-0.5 text-green-mid bg-green/10 border border-green/20">
              EAA Ready
            </span>
          ) : (
            <span className="font-mono text-[10px] uppercase tracking-widest px-2 py-0.5 text-fail bg-fail/10 border border-fail/20">
              EAA Action Required
            </span>
          )}
        </div>

        {/* Intro line */}
        <p className="text-secondary text-xs leading-relaxed mb-6 border-l-2 border-border pl-4">
          Generated by A11YO on {formatDate(scannedAt)} for{' '}
          <span className="text-white font-semibold">{url}</span>.{' '}
          Share this with your developer — every issue includes a plain English fix
          instruction and a step-by-step technical guide.
        </p>

        {/* URL + Score */}
        <div className="flex items-start justify-between gap-6 flex-wrap">
          <div className="min-w-0 flex-1">
            <a
              href={url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-white font-semibold hover:text-green transition-colors break-all block mb-1 text-lg"
            >
              {url}
            </a>
            <p className="font-mono text-xs text-secondary">{formatDate(scannedAt)}</p>
          </div>
          <div className="flex-shrink-0 text-right">
            <span className={`font-display text-6xl font-extrabold leading-none ${scoreColor(score)}`}>
              {score}<span className="text-3xl">%</span>
            </span>
            <p className="font-mono text-xs text-secondary mt-1">compliance score</p>
          </div>
        </div>
      </div>

      {/* Score bar */}
      <div className="h-1 bg-border">
        <div
          className="h-full transition-all"
          style={{ width: `${score}%`, backgroundColor: scoreBarColor(score) }}
        />
      </div>

      {/* Severity counts + actions */}
      <div className="px-6 py-4 flex flex-wrap items-center gap-x-8 gap-y-3">
        {[
          { count: critical_count, label: 'Critical', cls: 'text-fail' },
          { count: should_fix_count, label: 'Should Fix', cls: 'text-warn' },
          { count: nice_to_have_count, label: 'Nice to Have', cls: 'text-blue-400' },
          { count: passed_checks, label: 'Passed', cls: 'text-green-mid' },
        ].map(({ count, label, cls }) => (
          <div key={label} className="flex items-baseline gap-1.5">
            <span className={`font-mono text-2xl font-bold ${cls}`}>{count}</span>
            <span className="font-mono text-[10px] text-secondary uppercase tracking-widest">{label}</span>
          </div>
        ))}

        {reportId && (
          <div className="ml-auto">
            <a
              href={`/report/${reportId}/print`}
              target="_blank"
              rel="noopener noreferrer"
              className="font-mono text-xs tracking-wider uppercase bg-green text-black px-4 py-2 hover:bg-green-mid transition-colors whitespace-nowrap"
            >
              Download PDF →
            </a>
          </div>
        )}
      </div>

      {/* Next steps summary */}
      <div className="px-6 pb-5 border-t border-border pt-4">
        <p className="font-mono text-[10px] uppercase tracking-widest text-secondary mb-2">
          Recommended next step
        </p>
        <p className="text-secondary text-sm leading-relaxed">{nextStepsText}</p>
      </div>
    </div>
  );
}
