/**
 * F-007 — Sample Full Report (/sample-report)
 * Static, no auth required. Uses a realistic fictional Irish business.
 * Linked from homepage hero and footer — not main nav.
 * PRD ref: §F-007
 */
import type { Metadata } from 'next';
import Link from 'next/link';
import { ISSUE_LIBRARY, SEVERITY_CONFIG } from '@/lib/issue-library';
import IssueCard from '@/components/IssueCard';
import Logo from '@/components/Logo';

export const metadata: Metadata = {
  title: 'Sample Accessibility Report — A11YO',
  description:
    'See a real A11YO accessibility report for a fictional Irish business. Plain English issues, fix instructions, and a compliance score — no jargon.',
};

// Fictional Irish business: Keogh's Hardware, Athlone
const SAMPLE_URL = 'keoughshardware.ie';
const SAMPLE_DATE = '4 March 2026';
const SAMPLE_SCORE = 41;

// Issues the fictional site has — realistic mix
const CRITICAL_IDS = ['image-alt', 'form-labels', 'keyboard-focus', 'https'];
const SHOULD_FIX_IDS = ['meta-description', 'heading-structure', 'load-time', 'broken-links'];
const NICE_TO_HAVE_IDS = ['og-image', 'og-title', 'robots-txt', 'sitemap'];
const PASSED_IDS = ['color-contrast', 'title-lang', 'aria-errors', 'viewport', 'mobile-viewport'];

// Sample instance counts for realism
const COUNTS: Record<string, number> = {
  'image-alt': 23,
  'form-labels': 4,
  'keyboard-focus': 1,
  'heading-structure': 3,
  'broken-links': 5,
};

const SCORE_COLOR = SAMPLE_SCORE >= 80 ? 'text-green-mid' : SAMPLE_SCORE >= 50 ? 'text-warn' : 'text-fail';
const SCORE_BAR_COLOR = SAMPLE_SCORE >= 80 ? '#16A34A' : SAMPLE_SCORE >= 50 ? '#D97706' : '#DC2626';

function SectionHeader({ id, color, title, subtitle }: { id: string; color: string; title: string; subtitle: string }) {
  return (
    <div className="flex items-center gap-3 mb-3">
      <h2 id={id} className={`font-mono text-xs uppercase tracking-widest ${color}`}>{title}</h2>
      <span className="font-mono text-[10px] text-muted">— {subtitle}</span>
    </div>
  );
}

export default function SampleReportPage() {
  const criticalEntries = CRITICAL_IDS.map((id) => ISSUE_LIBRARY[id]).filter(Boolean);
  const shouldFixEntries = SHOULD_FIX_IDS.map((id) => ISSUE_LIBRARY[id]).filter(Boolean);
  const niceToHaveEntries = NICE_TO_HAVE_IDS.map((id) => ISSUE_LIBRARY[id]).filter(Boolean);
  const passedEntries = PASSED_IDS.map((id) => ISSUE_LIBRARY[id]).filter(Boolean);

  // Quick wins: entries flagged as quick wins from all issue buckets
  const quickWinEntries = [...criticalEntries, ...shouldFixEntries, ...niceToHaveEntries]
    .filter((e) => e.quickWin);

  return (
    <div className="min-h-screen bg-black flex flex-col">

      {/* Nav */}
      <header className="border-b border-border bg-black/90 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-white hover:text-green transition-colors" aria-label="A11YO home">
            <Logo size={28} />
          </Link>
          <Link href="/" className="font-mono text-xs tracking-wider uppercase text-secondary hover:text-white transition-colors">
            ← Get your own report
          </Link>
        </div>
      </header>

      {/* Sample banner */}
      <div className="bg-green/10 border-b border-green/20 px-6 py-3">
        <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 flex-wrap">
          <p className="font-mono text-xs text-green">
            This is a sample report for a fictional Irish business. Your real report will look exactly like this.
          </p>
          <Link
            href="/"
            className="font-mono text-xs tracking-wider uppercase bg-green text-black px-4 py-1.5 hover:bg-green-mid transition-colors whitespace-nowrap"
          >
            Scan your site free →
          </Link>
        </div>
      </div>

      <main id="main-content" className="flex-1 py-12 px-6">
        <div className="max-w-3xl mx-auto space-y-6">

          {/* ── 1. COVER SUMMARY ── */}
          <div className="corner-mark border border-border bg-surface">
            <div className="px-6 pt-6 pb-4">
              <span className="font-mono text-xs tracking-widest uppercase text-green block mb-4">
                Accessibility Report
              </span>
              <p className="text-secondary text-xs leading-relaxed mb-6 border-l-2 border-border pl-4">
                Generated by A11YO on {SAMPLE_DATE} for{' '}
                <span className="text-white font-semibold">{SAMPLE_URL}</span>.{' '}
                Share this with your developer — every issue below includes a plain English fix instruction.
                Tick each item as it is resolved.
              </p>

              <div className="flex items-start justify-between gap-6 flex-wrap">
                <div className="min-w-0 flex-1">
                  <span className="text-white font-semibold text-lg block mb-1">{SAMPLE_URL}</span>
                  <p className="font-mono text-xs text-secondary">{SAMPLE_DATE}</p>
                </div>
                <div className="flex-shrink-0 text-right">
                  <span className={`font-display text-6xl font-extrabold leading-none ${SCORE_COLOR}`}>
                    {SAMPLE_SCORE}<span className="text-3xl">%</span>
                  </span>
                  <p className="font-mono text-xs text-secondary mt-1">compliance score</p>
                </div>
              </div>
            </div>

            {/* Score bar */}
            <div className="h-1 bg-border">
              <div className="h-full" style={{ width: `${SAMPLE_SCORE}%`, backgroundColor: SCORE_BAR_COLOR }} />
            </div>

            {/* Severity counts */}
            <div className="px-6 py-4 flex flex-wrap items-center gap-x-8 gap-y-3">
              {[
                { count: criticalEntries.length, label: 'Critical', cls: 'text-fail' },
                { count: shouldFixEntries.length, label: 'Should Fix', cls: 'text-warn' },
                { count: niceToHaveEntries.length, label: 'Nice to Have', cls: 'text-blue-400' },
                { count: passedEntries.length, label: 'Passed', cls: 'text-green-mid' },
              ].map(({ count, label, cls }) => (
                <div key={label} className="flex items-baseline gap-1.5">
                  <span className={`font-mono text-2xl font-bold ${cls}`}>{count}</span>
                  <span className="font-mono text-[10px] text-secondary uppercase tracking-widest">{label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* ── 2. QUICK WINS ── */}
          {quickWinEntries.length > 0 && (
            <section aria-labelledby="qw-heading">
              <SectionHeader id="qw-heading" color="text-green" title="Quick Wins" subtitle="easy fixes — do these first regardless of severity" />
              <div className="space-y-2">
                {quickWinEntries.map((entry) => (
                  <IssueCard key={entry.id} entry={entry} count={COUNTS[entry.id]} />
                ))}
              </div>
            </section>
          )}

          {/* ── 3. CRITICAL ── */}
          <section aria-labelledby="critical-heading">
            <SectionHeader id="critical-heading" color="text-fail" title="Critical" subtitle="must fix before EAA deadline — legal risk" />
            <div className="space-y-2">
              {criticalEntries.map((entry) => (
                <IssueCard key={entry.id} entry={entry} count={COUNTS[entry.id]} defaultOpen={entry.id === 'image-alt'} />
              ))}
            </div>
          </section>

          {/* ── 4. SHOULD FIX ── */}
          <section aria-labelledby="should-fix-heading">
            <SectionHeader id="should-fix-heading" color="text-warn" title="Should Fix" subtitle="required for full EAA compliance" />
            <div className="space-y-2">
              {shouldFixEntries.map((entry) => (
                <IssueCard key={entry.id} entry={entry} count={COUNTS[entry.id]} />
              ))}
            </div>
          </section>

          {/* ── 5. NICE TO HAVE ── */}
          <section aria-labelledby="nth-heading">
            <SectionHeader id="nth-heading" color="text-blue-400" title="Nice to Have" subtitle="best practice — not legally required" />
            <div className="space-y-2">
              {niceToHaveEntries.map((entry) => (
                <IssueCard key={entry.id} entry={entry} />
              ))}
            </div>
          </section>

          {/* ── 6. WHAT PASSED ── */}
          <section aria-labelledby="passed-heading">
            <SectionHeader id="passed-heading" color="text-green" title="What Passed" subtitle={`${passedEntries.length} checks passed`} />
            <div className="corner-mark border border-border bg-surface divide-y divide-border">
              {passedEntries.map((entry) => (
                <div key={entry.id} className="px-5 py-3 flex items-center gap-3">
                  <span className="text-green-mid text-sm flex-shrink-0" aria-hidden="true">✓</span>
                  <span className="text-secondary text-sm">{entry.passTitle}</span>
                </div>
              ))}
            </div>
          </section>

          {/* ── 7. NEXT STEPS ── */}
          <section aria-labelledby="next-heading">
            <SectionHeader id="next-heading" color="text-green" title="Next Steps" subtitle="your plain English action plan" />
            <div className="corner-mark border border-border bg-surface px-6 py-5 space-y-3">
              <p className="text-secondary text-sm leading-relaxed">
                Start with the {criticalEntries.length} Critical issues. These block users entirely and carry legal risk under the EAA — fix them first. Then work through the {shouldFixEntries.length} Should Fix items to reach full EAA compliance.
              </p>
              <p className="text-secondary text-sm leading-relaxed">
                Forward this report to your developer. Every issue above includes a plain English fix instruction — they have everything they need to get started without any further briefing from you.
              </p>
            </div>
          </section>

          {/* ── CTA BANNER ── */}
          <div className="corner-mark border border-green/20 bg-surface px-6 py-7 text-center space-y-4">
            <span className="font-mono text-xs uppercase tracking-widest text-green block">
              This is a sample report
            </span>
            <h2 className="font-display text-2xl font-extrabold text-white">
              Get your own report — free
            </h2>
            <p className="text-secondary text-sm max-w-md mx-auto leading-relaxed">
              Enter your website URL and A11YO will scan it in seconds. No sign-up required for your first scan.
            </p>
            <Link
              href="/"
              className="inline-block font-mono text-sm tracking-wider uppercase bg-green text-black px-8 py-3 hover:bg-green-mid transition-colors"
            >
              Scan my website →
            </Link>
          </div>

        </div>
      </main>

      <footer className="border-t border-border px-6 py-5">
        <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 flex-wrap">
          <span className="font-mono text-xs text-secondary">
            Sample report — fictional business ·{' '}
            <Link href="/" className="text-green hover:underline">A11YO</Link>
          </span>
          <Link href="/accessibility" className="font-mono text-xs text-secondary hover:text-white transition-colors">
            Accessibility statement →
          </Link>
        </div>
      </footer>
    </div>
  );
}
